
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S1144:Unused private types or members should be removed", Justification = "<Ожидание>", Scope = "member", Target = "~M:App2.MainPage.CreateClusters")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S1144:Unused private types or members should be removed", Justification = "<Ожидание>", Scope = "member", Target = "~M:App2.MainPage.run_cmd(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Bug", "S2201:Return values from functions without side effects should not be ignored", Justification = "<Ожидание>", Scope = "member", Target = "~M:App2.MainPage.Lemmatize(System.Collections.Generic.SortedSet{System.String})~System.Collections.Generic.SortedSet{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Bug", "S2201:Return values from functions without side effects should not be ignored", Justification = "<Ожидание>", Scope = "member", Target = "~M:App2.MainPage.Covering(System.Collections.Generic.List{System.Collections.Generic.List{System.Double}})~System.Collections.Generic.List{System.Collections.Generic.List{System.Double}}")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Bug", "S2201:Return values from functions without side effects should not be ignored", Justification = "<Ожидание>", Scope = "member", Target = "~M:App2.MainPage.ClustersCounting(System.Collections.Generic.List{System.Collections.Generic.List{System.Double}})~System.Int32")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Bug", "S2201:Return values from functions without side effects should not be ignored", Justification = "<Ожидание>", Scope = "member", Target = "~M:App2.MainPage.Priming(System.Collections.Generic.List{System.Collections.Generic.List{System.Double}},System.Collections.Generic.List{System.Collections.Generic.List{System.Double}})~System.Collections.Generic.List{System.Tuple{System.Double,System.Int32}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Bug", "S2201:Return values from functions without side effects should not be ignored", Justification = "<Ожидание>", Scope = "member", Target = "~M:App2.MainPage.CCCM(System.Collections.Generic.List{System.Collections.Generic.List{System.Double}})~System.Collections.Generic.List{System.Collections.Generic.List{System.Int32}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Bug", "S2201:Return values from functions without side effects should not be ignored", Justification = "<Ожидание>", Scope = "member", Target = "~M:App2.MainPage.CreateDocsTermsMatrix(System.Collections.Generic.List{System.Collections.Generic.SortedSet{System.String}},System.Collections.Generic.SortedSet{System.String})~System.Collections.Generic.List{System.Collections.Generic.List{System.Double}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Bug", "S2201:Return values from functions without side effects should not be ignored", Justification = "<Ожидание>", Scope = "member", Target = "~M:App2.MainPage.CreateClusters")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S3358:Ternary operators should not be nested", Justification = "<Ожидание>", Scope = "member", Target = "~M:App2.MainPage.ArgMax(System.Collections.Generic.IEnumerable{System.Double})~System.Int32")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S1144:Unused private types or members should be removed", Justification = "<Ожидание>", Scope = "member", Target = "~M:App2.MainPage.AllTermsTest")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S125:Sections of code should not be \"commented out\"", Justification = "<Ожидание>", Scope = "member", Target = "~M:App2.MainPage.AllTermsTest")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S125:Sections of code should not be \"commented out\"", Justification = "<Ожидание>", Scope = "member", Target = "~M:App2.MainPage.LoginButton_Click(System.Object,Windows.UI.Xaml.RoutedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S1144:Unused private types or members should be removed", Justification = "<Ожидание>", Scope = "member", Target = "~M:App2.MainPage.WordsTest")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Bug", "S2201:Return values from functions without side effects should not be ignored", Justification = "<Ожидание>", Scope = "member", Target = "~M:App2.MainPage.CreateClusters(System.Collections.Generic.SortedSet{VkNet.Model.Group})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S3358:Ternary operators should not be nested", Justification = "<Ожидание>", Scope = "member", Target = "~M:App2.TestsPage.ArgMax(System.Collections.Generic.IEnumerable{System.Double})~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Bug", "S2201:Return values from functions without side effects should not be ignored", Justification = "<Ожидание>", Scope = "member", Target = "~M:App2.TestsPage.CCCM(System.Collections.Generic.List{System.Collections.Generic.List{System.Double}})~System.Collections.Generic.List{System.Collections.Generic.List{System.Int32}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S125:Sections of code should not be \"commented out\"", Justification = "<Ожидание>", Scope = "member", Target = "~M:App2.TestsPage.Lemmatize(System.Collections.Generic.SortedSet{System.String})~System.Collections.Generic.HashSet{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S125:Sections of code should not be \"commented out\"", Justification = "<Ожидание>", Scope = "member", Target = "~M:App2.TestsPage.ClustersTest")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S1144:Unused private types or members should be removed", Justification = "<Ожидание>", Scope = "member", Target = "~M:App2.TestsPage.AllTermsTest")]

